# Generated by Django 3.0 on 2022-11-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPermissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenpermissions',
            options={'permissions': (('GreenSystemAdmin', 'GreenSystemAdmin'), ('GreenPermissions', 'GreenPermissions'), ('GreenWaterSystem', 'GreenWatherSystem'), ('GreenWeedSystem', 'GreenWeedSystem'), ('GreenSeedSystem', 'GreenSeedSystem'), ('GreenCameraOne', 'GreenCameraOne'), ('GreenCameraTwo', 'GreenCameraTwo'), ('GreenDatabase', 'GreenDatabase'))},
        ),
    ]
