# Generated by Django 3.0 on 2022-11-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPermissions', '0002_auto_20221128_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenpermissions',
            options={'permissions': (('GreenSystemAdmin', 'GreenSystemAdmin'), ('GreenAddPermissions', 'GreenAddPermissions'), ('GreenWaterSystem', 'GreenWatherSystem'), ('GreenWeedSystem', 'GreenWeedSystem'), ('GreenSeedSystem', 'GreenSeedSystem'), ('GreenCameraOne', 'GreenCameraOne'), ('GreenCameraTwo', 'GreenCameraTwo'), ('GreenDatabase', 'GreenDatabase'))},
        ),
    ]
