# Generated by Django 3.0 on 2022-12-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPermissions', '0003_auto_20221130_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenpermissions',
            options={'permissions': (('GreenSystemAdmin', 'GreenSystemAdmin'), ('GreenSystemUser', 'GreenSystemUser'), ('GreenSystemGuest', 'GreenSystemGuest'), ('GreenAddPermissions', 'GreenAddPermissions'), ('GreenWaterSystem', 'GreenWatherSystem'), ('GreenWeedSystem', 'GreenWeedSystem'), ('GreenSeedSystem', 'GreenSeedSystem'), ('GreenCameraOne', 'GreenCameraOne'), ('GreenCameraTwo', 'GreenCameraTwo'), ('GreenDatabase', 'GreenDatabase'))},
        ),
    ]
